### ISSUE TITLE
3 properties in "New Project" section

### ISSUE THREAD

**Issue by anusharish** [priyambada12/HOMES247#13]
Three properties should be displaying in the "New Projects" Section

1. Open link:- http://18.218.16.184/HOMES24_7/#/dashboard

**Comment by priyambada12** [comment]
in earlier design(According to client requirement), it is 2 properties...
Why You want 3 properties in new project?

**Comment by GVHarish** [comment]
Client requirement is to display three images and should padding as in the design 

Please Refer the below link 
[http://betaphase.in/homes247/index.html](http://betaphase.in/homes247/index.html)

![image](https://user-images.githubusercontent.com/37058551/37402186-958719ee-27b0-11e8-9e86-ca3dc7bc180f.png)
