### ISSUE TITLE
Success message is displaying wrongly. Says "You will intimate you soon"

### ISSUE THREAD

**Issue by anusharish** [priyambada12/HOMES247#20]
Success message is displaying wrongly. Says "You will intimate you soon"

1. Open link:- http://18.218.16.184/HOMES24_7/#/dashboard
2. Click on NRI Services
3. Enter Valid Name, Mobile Number, Email Id and a Message
4. Click on SUBMIT

**Comment by GVHarish** [comment]
The issue is not yet solved. Error message success message is still displaying as "You will intimate you Soon"

![image](https://user-images.githubusercontent.com/37058551/37578391-88c2f21c-2b5e-11e8-9c10-edca51ce65a3.png)
