### ISSUE TITLE
Page doesnot scroll to top when user clicks on a link in the footer

### ISSUE THREAD

**Issue by anusharish** [priyambada12/HOMES247#30]
Page doesnot scroll to top when user clicks on a link in the footer

1. Open link:- http://18.218.16.184/HOMES24_7/#/dashboard
2. Click on NRI Services, Home loan, Properties For Sale In Bengaluru

**Comment by GVHarish** [comment]
Happens to all the links on the website. 
When Clicked on a link or reload a page, The footer will be displayed first while loading.

**Comment by priyambada12** [comment]
I will resolve it today...

**Comment by GVHarish** [comment]
When a page is being loaded, the footer will display first and then the page will load
