### ISSUE TITLE
Name and location of the property will not display when no images are added

### ISSUE THREAD

**Issue by GVHarish** [priyambada12/HOMES247#62]
OS:- Windows 7
Browser:- Chrome(64.0.3282.186)

Steps:-
1. Open Link:- Login to backend
2. Add a property
3. Edit the same property and delete All the images
4. Open Link:- http://18.218.16.184/HOMES24_7 
5. Open the added property

Description:- Name and location of the property will not display when no images are added.

![3](https://user-images.githubusercontent.com/37058551/37029681-52dbfa5e-215e-11e8-973b-1e7acdde8f9e.png)

**Comment by priyambada12** [comment]
unable to replicate the issue.
