### ISSUE TITLE
Scroll option in "Top projects" section

### ISSUE THREAD

**Issue by anusharish** [priyambada12/HOMES247#8]
Option to scroll the slider is not provided for the section "Top Projects"

1. Open link:- http://18.218.16.184/HOMES24_7/#/dashboard

**Comment by GVHarish** [comment]
The design of the arrows is not as proposed

as displayed below..
![image](https://user-images.githubusercontent.com/37058551/37399752-a65c51b0-27a8-11e8-91af-314dfa61703d.png)
